os: Visual Studio 2017

version: '{build}'

environment:
  BUCK_EXTRA_JAVA_ARGS: "-Djna.nosys=true"
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - ps: choco install wget -y --no-progress
  - ps: choco install zip -y --no-progress
  - ps: choco install buck -y --no-progress
  - ps: refreshenv
  - ps: choco list --localonly
  - ps: buck --version
  - wget -q -O buckaroo-cli.jar https://github.com/LoopPerfect/buckaroo/releases/download/v1.4.1/buckaroo-cli.jar

# Disable automatic builds by MSBuild
build: off

build_script:
  - java -jar buckaroo-cli.jar install

test_script:
  - buck test :test1

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
